// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQcmZh9YaLkg43HX3qSib7qHr8PSc5jSM',
    appId: '1:244051247756:web:9292e280da0880937c71a9',
    messagingSenderId: '244051247756',
    projectId: 'furute-fefa1',
    authDomain: 'furute-fefa1.firebaseapp.com',
    databaseURL: 'https://furute-fefa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'furute-fefa1.firebasestorage.app',
    measurementId: 'G-15MZYMNY32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99v6kzJO5LCgQcZvA3ZuuYpQ6jt0_9F0',
    appId: '1:244051247756:android:c83b13fce76349217c71a9',
    messagingSenderId: '244051247756',
    projectId: 'furute-fefa1',
    databaseURL: 'https://furute-fefa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'furute-fefa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVoRMuexiv2KD9o1y3s0BjPtnsLKoEO0M',
    appId: '1:244051247756:ios:821a002df5616ea07c71a9',
    messagingSenderId: '244051247756',
    projectId: 'furute-fefa1',
    databaseURL: 'https://furute-fefa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'furute-fefa1.firebasestorage.app',
    androidClientId: '244051247756-7vjm1s58jmrk01v8opc9ek4orhjpar3v.apps.googleusercontent.com',
    iosClientId: '244051247756-i8idqh0narptlff19ijn3gnhutpdeonq.apps.googleusercontent.com',
    iosBundleId: 'com.example.furute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVoRMuexiv2KD9o1y3s0BjPtnsLKoEO0M',
    appId: '1:244051247756:ios:2cb2cb6abee2dd2e7c71a9',
    messagingSenderId: '244051247756',
    projectId: 'furute-fefa1',
    databaseURL: 'https://furute-fefa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'furute-fefa1.firebasestorage.app',
    androidClientId: '244051247756-7vjm1s58jmrk01v8opc9ek4orhjpar3v.apps.googleusercontent.com',
    iosClientId: '244051247756-fuumk4khn8ittd8es1dbf8gkbnhm7ft3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frutesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQcmZh9YaLkg43HX3qSib7qHr8PSc5jSM',
    appId: '1:244051247756:web:80733d79553d797a7c71a9',
    messagingSenderId: '244051247756',
    projectId: 'furute-fefa1',
    authDomain: 'furute-fefa1.firebaseapp.com',
    databaseURL: 'https://furute-fefa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'furute-fefa1.firebasestorage.app',
    measurementId: 'G-PJHEDFV6LF',
  );

}