default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk  --release -t lib/main_prod.dart --flavor prod --no-tree-shake-icons"
    release = firebase_app_distribution(
            app: "1:244051247756:android:4949f37a25d791ef7c71a9",
            firebase_cli_token: "1//032SbOH4_sBvMCgYIARAAGAMSNwF-L9Irtp4V0t61gNa4Ws-8XQuPlUn4ybmEZKieech8-kBNNBGelqnHwV5V2on_q0SiiQo5agg",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
            testers: "mohamedelmelegydeveloper@gmail.com",
            release_notes: "Test Details Item Page ",
            )
    end
  end
  
# fastlane add_plugin firebase_app_distribution
# fastlane android firebase_distribution
